feat: make gh optional (fallback on jq)

diff --git a/spexup b/spexup
--- a/spexup
+++ b/spexup
@@ -32,14 +32,25 @@ main () {
   check_terminal_ansi_support
 
   need_cmd curl
-  need_cmd gh
+  need_cmd awk
   need_cmd uname
   need_cmd chmod
   need_cmd mkdir
   need_cmd ln
 
-  gh auth status >/dev/null 2>&1 || \
-      echo "${GH_TOKEN}" | gh auth login --with-token
+  if check_cmd "gh"; then
+    USE_GH=true
+  elif check_cmd "jq"; then
+    USE_GH=false
+  else
+    err "need 'jq' or 'gh' (command not found)"
+    exit 1
+  fi
+
+  if [ "$USE_GH" ]; then
+    gh auth status >/dev/null 2>&1 || \
+        echo "${GH_TOKEN}" | gh auth login --with-token
+  fi
 
   get_architecture || return 1
   local _arch="$RETVAL"
@@ -125,18 +136,31 @@ bug with the \n       output of 'uname -a'."
 
 latest_release () {
   local _repo="$1"
-  gh release list --repo "${OWNER}/$_repo" \
-      --exclude-drafts --limit 1 --json tagName --jq '.[].tagName'
+  if [ "$USE_GH" ]; then
+    gh release list --repo "${OWNER}/$_repo" \
+        --exclude-drafts --limit 1 --json tagName --jq '.[].tagName'
+  else
+    downloader "https://api.github.com/repos/$OWNER/$_repo/releases" \
+      | jq -r '.[].tag_name'
+  fi
 }
 
 binary_assets () {
   local _repo="$1"
   local _version="$2"
   local _platform="$3"
-  gh api https://api.github.com/repos/spex-lang/spex/releases --jq \
-    ".[] | select(.tag_name == \"$_version\") | \
-     .assets[] | select(.name | contains(\"$_platform\")) | \
-     .browser_download_url"
+
+  if [ "$USE_GH" ]; then
+    gh api https://api.github.com/repos/spex-lang/spex/releases --jq \
+      ".[] | select(.tag_name == \"$_version\") | \
+       .assets[] | select(.name | contains(\"$_platform\")) | \
+       .browser_download_url"
+  else
+    downloader "https://api.github.com/repos/$OWNER/$_repo/releases" \
+      | jq -r ".[] | select(.tag_name == \"$_version\") | \
+               .assets[] | select(.name | contains(\"$_platform\")) | \
+               .browser_download_url"
+  fi
 }
 
 # ------------------------------------------------------------------------
@@ -173,6 +197,36 @@ check_terminal_ansi_support () {
       fi
     fi
   fi
+}
+
+downloader() {
+    local _url="$1"
+    if [ -n "${GH_TOKEN+x}" ]; then
+        curl \
+            --header "Authorization: Bearer ${GH_TOKEN}" \
+            --header "Accept: application/vnd.github+json" \
+            --header "X-GitHub-Api-Version: 2022-11-28" \
+            --header "User-Agent: spex-lang/spexup" \
+            --silent \
+            --show-error \
+            --fail \
+            --location \
+            --retry 3 \
+            --continue-at - \
+            "$_url"
+    else
+        curl \
+            --header "Accept: application/vnd.github+json" \
+            --header "X-GitHub-Api-Version: 2022-11-28" \
+            --header "User-Agent: spex-lang/spexup" \
+            --silent \
+            --show-error \
+            --fail \
+            --location \
+            --retry 3 \
+            --continue-at - \
+            "$_url"
+    fi
 }
 
 say() {
